Time dependent inputs testing
neurolib-dev/neurolib pull request #211
Opened 2022-06-08 14:20 UTC by lenasal

Include time-dependent inputs to the FHN model, the WC model, and the Hopf model.
- move "adjust_shape" function from aln time integration file to general file in utils
- fix bug in test_models
- add tests for stimulation of FHN, WC, Hopf

2022-06-15 09:25 UTC, caglorithm commented
* Tests still failing. 
* PR contains changes in notebooks. 
* Changes in parameter names need to be reverted everywhere (also in tests).

2022-06-16 08:41 UTC, lenasal commented
I've updated things, test are not failing anymore.

2022-06-16 12:46 UTC, lenasal commented
changed index of inputs in time integration, this way it is more in line with the aln model (and also, I personally think it makes more sense)

2022-06-17 12:18 UTC, caglorithm commented
Nice! Could you also remove your commits for the notebooks from the PR?

2022-06-17 12:21 UTC, caglorithm requested changes
Please see the one nit comment I've made!

2022-06-17 12:21 UTC, caglorithm commented on neurolib/models/hopf/loadDefaultParams.py
> -    params.y_ext = np.zeros((params.N,))
Leaving these lines the way they are should work as well, right?

2022-06-20 12:08 UTC, caglorithm commented
LGTM. Merging after tests finish ✅.

2022-06-20 12:48 UTC, merged